[IOP] : Adding New Metrics controllers to push metrics to prometheus
cloudfoundry/service-fabrik-broker pull request #1847
Opened 2023-03-14 12:45 UTC by vinaybheri

* Currently the sfserviceinstance metrics are sent from sfserviceinstancereplicator controller. For better channelization and readability now we have created new controller sfserviceinstancemetrics to push  sfserviceinstance metrics to prometheus.
* Similarly till now the sfservicebinding metrics are sent from sfservicebindingreplicator controller. For better channelization and readability now we have created a new controller sfservicebindingmetrics to push  sfservicebinding metrics to prometheus.

2023-06-08 09:16 UTC, jintusebastian requested changes
Looks like some commits are unrelated to this PR: 762c3598726a85d1aee91f529658460f504de421

Please rebase the branch with master

2023-06-09 05:58 UTC, vinaybheri commented
@jintusebastian Updated changes with latest master branch changes.
Kindly check and review.

2023-06-20 07:36 UTC, anoopjb commented on interoperator/controllers/multiclusterdeploy/sfservicebindingmetrics/sfservicebindingmetrics_controller.go
> +// BindingReplicator replicates sfserviceinstance
I see the comments are outdated. Please update the inline comments.

2023-06-20 07:41 UTC, anoopjb commented on interoperator/controllers/multiclusterdeploy/sfserviceinstancemetrics/sfserviceinstancemetrics_controller.go
> +// and replicates it.
I think these outdated comments will mislead the functionality of the method.

2023-06-20 08:04 UTC, anoopjb commented on interoperator/controllers/multiclusterdeploy/sfserviceinstancemetrics/sfserviceinstancemetrics_controller_test.go
> +	//"k8s.io/client-go/util/retry"
```suggestion
```

I think it is good to remove the unused comments.

2023-06-20 08:10 UTC, anoopjb approved these changes
LGTM :+1:

2023-06-20 08:24 UTC, merged